/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
          50: 'hsl(var(--nutri-50))',
          100: 'hsl(var(--nutri-100))',
          200: 'hsl(var(--nutri-200))',
          300: 'hsl(var(--nutri-300))',
          400: 'hsl(var(--nutri-400))',
          500: 'hsl(var(--nutri-500))',
          600: 'hsl(var(--nutri-600))',
          700: 'hsl(var(--nutri-700))',
          800: 'hsl(var(--nutri-800))',
          900: 'hsl(var(--nutri-900))',
          950: 'hsl(var(--nutri-950))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        nutri: {
          50: 'hsl(var(--nutri-50))',
          100: 'hsl(var(--nutri-100))',
          200: 'hsl(var(--nutri-200))',
          300: 'hsl(var(--nutri-300))',
          400: 'hsl(var(--nutri-400))',
          500: 'hsl(var(--nutri-500))',
          600: 'hsl(var(--nutri-600))',
          700: 'hsl(var(--nutri-700))',
          800: 'hsl(var(--nutri-800))',
          900: 'hsl(var(--nutri-900))',
          950: 'hsl(var(--nutri-950))',
        },
        success: {
          DEFAULT: 'hsl(var(--success))',
          foreground: 'hsl(var(--success-foreground))',
          light: 'hsl(var(--success-light))',
          dark: 'hsl(var(--success-dark))',
        },
        warning: {
          DEFAULT: 'hsl(var(--warning))',
          foreground: 'hsl(var(--warning-foreground))',
          light: 'hsl(var(--warning-light))',
          dark: 'hsl(var(--warning-dark))',
        },
        error: {
          DEFAULT: 'hsl(var(--error))',
          foreground: 'hsl(var(--error-foreground))',
          light: 'hsl(var(--error-light))',
          dark: 'hsl(var(--error-dark))',
        },
        info: {
          DEFAULT: 'hsl(var(--info))',
          foreground: 'hsl(var(--info-foreground))',
          light: 'hsl(var(--info-light))',
          dark: 'hsl(var(--info-dark))',
        },
        surface: {
          level0: 'hsl(var(--surface-level0))',
          level1: 'hsl(var(--surface-level1))',
          level2: 'hsl(var(--surface-level2))',
          level3: 'hsl(var(--surface-level3))',
        },
        text: {
          primary: 'hsl(var(--text-primary))',
          secondary: 'hsl(var(--text-secondary))',
          tertiary: 'hsl(var(--text-tertiary))',
          inverse: 'hsl(var(--text-inverse))',
          disabled: 'hsl(var(--text-disabled))',
          link: 'hsl(var(--text-link))',
        },
        status: {
          agendada: {
            bg: 'hsl(var(--status-agendada-bg))',
            text: 'hsl(var(--status-agendada-text))',
            border: 'hsl(var(--status-agendada-border))',
          },
          confirmada: {
            bg: 'hsl(var(--status-confirmada-bg))',
            text: 'hsl(var(--status-confirmada-text))',
            border: 'hsl(var(--status-confirmada-border))',
          },
          realizada: {
            bg: 'hsl(var(--status-realizada-bg))',
            text: 'hsl(var(--status-realizada-text))',
            border: 'hsl(var(--status-realizada-border))',
          },
          cancelada: {
            bg: 'hsl(var(--status-cancelada-bg))',
            text: 'hsl(var(--status-cancelada-text))',
            border: 'hsl(var(--status-cancelada-border))',
          },
          nao_compareceu: {
            bg: 'hsl(var(--status-nao-compareceu-bg))',
            text: 'hsl(var(--status-nao-compareceu-text))',
            border: 'hsl(var(--status-nao-compareceu-border))',
          },
          ativo: {
            bg: 'hsl(var(--status-ativo-bg))',
            text: 'hsl(var(--status-ativo-text))',
          },
          manutencao: {
            bg: 'hsl(var(--status-manutencao-bg))',
            text: 'hsl(var(--status-manutencao-text))',
          },
          inativo: {
            bg: 'hsl(var(--status-inativo-bg))',
            text: 'hsl(var(--status-inativo-text))',
          },
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'Consolas', 'monospace'],
      },
      fontSize: {
        'display-lg': ['57px', { lineHeight: '64px', fontWeight: '400', letterSpacing: '-0.25%' }],
        'display-md': ['45px', { lineHeight: '52px', fontWeight: '400', letterSpacing: '0%' }],
        'display-sm': ['36px', { lineHeight: '44px', fontWeight: '400', letterSpacing: '0%' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600', letterSpacing: '0%' }],
        'headline-md': ['28px', { lineHeight: '36px', fontWeight: '600', letterSpacing: '0%' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600', letterSpacing: '0%' }],
        'title-lg': ['22px', { lineHeight: '28px', fontWeight: '600', letterSpacing: '0%' }],
        'title-md': ['16px', { lineHeight: '24px', fontWeight: '600', letterSpacing: '0.15%' }],
        'title-sm': ['14px', { lineHeight: '20px', fontWeight: '600', letterSpacing: '0.1%' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400', letterSpacing: '0.15%' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400', letterSpacing: '0.25%' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400', letterSpacing: '0.4%' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '600', letterSpacing: '0.1%' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.5%' }],
        'label-sm': ['11px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.5%' }],
      },
      spacing: {
        '0': '0px',
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '8': '32px',
        '10': '40px',
        '12': '48px',
        '16': '64px',
        '20': '80px',
        '24': '96px',
        'touch-min': '44px',
        'touch-comfortable': '48px',
      },
      borderRadius: {
        none: '0px',
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        full: '9999px',
        DEFAULT: 'var(--radius)',
      },
      boxShadow: {
        level0: 'none',
        level1: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        level2: '0 4px 8px -2px rgba(0, 0, 0, 0.08), 0 2px 4px -2px rgba(0, 0, 0, 0.04)',
        level3: '0 8px 16px -4px rgba(0, 0, 0, 0.12), 0 4px 8px -4px rgba(0, 0, 0, 0.06)',
        level4: '0 16px 24px -8px rgba(0, 0, 0, 0.16), 0 8px 16px -8px rgba(0, 0, 0, 0.08)',
      },
      transitionDuration: {
        instant: '0ms',
        fast: '150ms',
        normal: '250ms',
        slow: '350ms',
        slower: '500ms',
      },
      transitionTimingFunction: {
        standard: 'cubic-bezier(0.2, 0, 0.38, 0.9)',
        entrance: 'cubic-bezier(0, 0, 0.2, 1)',
        exit: 'cubic-bezier(0.4, 0, 1, 1)',
        emphasized: 'cubic-bezier(0.05, 0.7, 0.1, 1)',
      },
      animation: {
        'skeleton-pulse': 'skeleton-pulse 1.2s ease-in-out infinite',
        'fade-in': 'fade-in 200ms ease-out',
        'slide-up': 'slide-up 300ms cubic-bezier(0, 0, 0.2, 1)',
        'slide-down': 'slide-down 200ms cubic-bezier(0.4, 0, 1, 1)',
        'scale-in': 'scale-in 150ms cubic-bezier(0.05, 0.7, 0.1, 1)',
      },
      keyframes: {
        'skeleton-pulse': {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'slide-up': {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-down': {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'scale-in': {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
};